"""
Brute force search for optimal quantum codes with time vortices.

Searches over unique 4D lattices and vortex configurations to find codes
with best distance and logical error rates for each (n, k) pair.
"""

import numpy as np
import csv
import itertools
import ast
import sys
import os
from typing import List, Dict, Tuple, Optional, Any
from tqdm import tqdm
import sinter
import tesseract_decoder.tesseract_sinter_compat as tesseract_sinter

from lattice import Lattice
from qubit_system import QubitSystem
from gate_order import GateOrder, GateDescriptor
from syndrome_circuit import SyndromeCircuit
from plot_threshold import calculate_wilson_confidence_interval


def load_lattices_from_csv(csv_file: str, max_n: int = 30) -> List[List[List[int]]]:
    """
    Load unique lattices from CSV file generated by generate_4d_lattices.py.
    
    Args:
        csv_file: Path to CSV file with lattice vectors
        max_n: Maximum number of physical qubits (n = 4 * |det|)
    
    Returns:
        List of lattices, each as list of 4 vectors
    """
    lattices = []
    
    with open(csv_file, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                # Parse lattice vectors from strings
                vec0 = ast.literal_eval(row['lattice_vec_0'])
                vec1 = ast.literal_eval(row['lattice_vec_1'])
                vec2 = ast.literal_eval(row['lattice_vec_2'])
                vec3 = ast.literal_eval(row['lattice_vec_3'])
                
                lattice_vectors = [vec0, vec1, vec2, vec3]
                
                # Calculate determinant and check n constraint
                B = np.array(lattice_vectors, dtype=int)
                det = abs(np.linalg.det(B))
                n = int(4 * det)
                
                if n <= max_n:
                    lattices.append(lattice_vectors)
            except Exception as e:
                print(f"Warning: Failed to parse lattice row: {e}")
                continue
    
    return lattices


def search_codes_with_vortices(
    input_csv: str = 'unique_4d_lattices.csv',
    p_phenomenological: float = 0.02,
    p_cx: float = 0.0,
    shots_per_point: int = 100000,
    max_n: int = 30,
    num_workers: int = 4,
    max_errors: int = 100,
    num_noisy_cycles: int = 4,
    num_noiseless_cycles_init: int = 3,
    num_noiseless_cycles_final: int = 3,
    basis: str = 'Z',
    output_csv: str = 'search_results.csv',
    summary_csv: str = 'best_codes_summary.csv',
    checkpoint_interval: int = 10
):
    """
    Perform brute force search over lattices and vortex configurations.
    
    Args:
        input_csv: Input CSV file with unique lattices
        p_phenomenological: Phenomenological error rate
        p_cx: CNOT gate error rate
        shots_per_point: Number of shots per configuration
        max_n: Maximum number of physical qubits
        num_workers: Number of parallel workers for sinter
        max_errors: Maximum errors before stopping
        num_noisy_cycles: Number of noisy cycles
        num_noiseless_cycles_init: Number of initial noiseless cycles
        num_noiseless_cycles_final: Number of final noiseless cycles
        basis: Measurement basis ('Z' or 'X')
        output_csv: Output CSV file for detailed results
        summary_csv: Output CSV file for best codes summary
        checkpoint_interval: Save checkpoint every N lattices
    """
    print("=== Brute Force Code Search with Time Vortices ===")
    print(f"Input file: {input_csv}")
    print(f"Phenomenological noise: p = {p_phenomenological}")
    print(f"Shots per configuration: {shots_per_point}")
    print(f"Max physical qubits (n): {max_n}")
    print(f"Basis: {basis}")
    print()
    
    # Load lattices
    print(f"Loading lattices from {input_csv}...")
    lattices = load_lattices_from_csv(input_csv, max_n=max_n)
    print(f"Loaded {len(lattices)} lattices (n <= {max_n})")
    
    # Generate all vortex configurations
    vortex_values = [0, -1, 1]
    all_vortex_configs = list(itertools.product(vortex_values, vortex_values, [0], [0]))
    print(f"Testing {len(all_vortex_configs)} vortex configurations per lattice")
    print()
    
    # BB gate order
    bb_gate_order = GateOrder([
        GateDescriptor("Z", "on_site_L"),
        GateDescriptor("X", "axis_0"), GateDescriptor("Z", "axis_2"),
        GateDescriptor("X", "axis_1"), GateDescriptor("Z", "on_site_R"),
        GateDescriptor("X", "on_site_L"), GateDescriptor("Z", "axis_1"),
        GateDescriptor("X", "axis_3"), GateDescriptor("Z", "axis_3"),
        GateDescriptor("X", "on_site_R"), GateDescriptor("Z", "axis_0"),
        GateDescriptor("X", "axis_2")
    ])
    # # all Zs then all Xs
    # bb_gate_order = GateOrder([
    #     GateDescriptor("Z", "on_site_L"),
    #     GateDescriptor("Z", "axis_2"),
    #     GateDescriptor("Z", "on_site_R"),
    #     GateDescriptor("Z", "axis_1"),
    #     GateDescriptor("Z", "axis_3"),
    #     GateDescriptor("Z", "axis_0"),
    #     GateDescriptor("X", "axis_0"),
    #     GateDescriptor("X", "axis_1"), 
    #     GateDescriptor("X", "on_site_L"), 
    #     GateDescriptor("X", "axis_3"), 
    #     GateDescriptor("X", "on_site_R"),
    #     GateDescriptor("X", "axis_2")
    # ])
    
    # Best code tracking dictionaries keyed by (n, k)
    best_by_distance_arbitrary: Dict[Tuple[int, int], Dict[str, Any]] = {}
    best_by_distance_zero_vortex: Dict[Tuple[int, int], Dict[str, Any]] = {}
    best_by_error_rate_arbitrary: Dict[Tuple[int, int], Dict[str, Any]] = {}
    best_by_error_rate_zero_vortex: Dict[Tuple[int, int], Dict[str, Any]] = {}
    
    # Detailed results
    all_results = []
    
    # CSV fieldnames for detailed results
    result_fieldnames = [
        'lattice_vec_0', 'lattice_vec_1', 'lattice_vec_2', 'lattice_vec_3',
        'vortex_0', 'vortex_1', 'vortex_2', 'vortex_3',
        'n', 'k', 'distance', 'logical_error_rate', 'error_bar',
        'shots', 'errors', 'p_phenomenological'
    ]
    
    # Initialize output CSV
    with open(output_csv, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=result_fieldnames)
        writer.writeheader()
    
    # Statistics
    total_tested = 0
    successful = 0
    failed = 0
    
    # Search loop
    for lattice_idx, lattice_vectors in enumerate(tqdm(lattices, desc="Lattices")):
        try:
            # Create lattice and qubit system
            lattice = Lattice(lattice_vectors)
            qubit_system = QubitSystem(lattice)
            lattice_points = lattice.get_all_lattice_points()
            
            # Calculate n (physical qubits)
            det = abs(np.linalg.det(np.array(lattice_vectors, dtype=int)))
            n = int(4 * det)
            
            if n > max_n:
                continue
            
            # Test each vortex configuration
            for vortex_counts_tuple in all_vortex_configs:
                vortex_counts = list(vortex_counts_tuple)
                total_tested += 1
                
                try:
                    # Build SyndromeCircuit
                    circuit = SyndromeCircuit(
                        qubit_system=qubit_system,
                        lattice_points=lattice_points,
                        gate_order=bb_gate_order,
                        num_noisy_cycles=num_noisy_cycles,
                        num_noiseless_cycles_init=num_noiseless_cycles_init,
                        num_noiseless_cycles_final=num_noiseless_cycles_final,
                        p_cx=p_cx,
                        p_phenomenological=p_phenomenological,
                        basis=basis,
                        include_observables=True,
                        vortex_counts=vortex_counts
                    )
                    
                    # Calculate k (logical qubits)
                    k = circuit.logical_operators.get_num_logical_qubits()
                    
                    # Generate Stim circuit
                    stim_circuit = circuit.to_stim_circuit()
                    
                    # Calculate distance
                    distance = None
                    try:
                        minimal_found_error = stim_circuit.search_for_undetectable_logical_errors(
                            dont_explore_detection_event_sets_with_size_above=6,
                            dont_explore_edges_with_degree_above=9999,
                            dont_explore_edges_increasing_symptom_degree=False,
                            canonicalize_circuit_errors=True
                        )
                        distance = len(minimal_found_error)
                    except Exception as e:
                        print(f"Warning: Distance calculation failed: {e}")
                        distance = None
                    
                    # Calculate logical error rate
                    def get_tesseract_decoder_for_sinter():
                        return {"tesseract": tesseract_sinter.TesseractSinterDecoder()}
                    
                    results_sinter, = sinter.collect(
                        num_workers=num_workers,
                        tasks=[sinter.Task(circuit=stim_circuit)],
                        decoders=["tesseract"],
                        max_shots=shots_per_point,
                        max_errors=max_errors,
                        custom_decoders=get_tesseract_decoder_for_sinter(),
                    )
                    
                    # Calculate logical error rate and confidence interval
                    logical_error_rate, error_bar = calculate_wilson_confidence_interval(
                        results_sinter.errors, results_sinter.shots
                    )
                    
                    # Store result
                    result = {
                        'lattice_vec_0': str(lattice_vectors[0]),
                        'lattice_vec_1': str(lattice_vectors[1]),
                        'lattice_vec_2': str(lattice_vectors[2]),
                        'lattice_vec_3': str(lattice_vectors[3]),
                        'vortex_0': vortex_counts[0],
                        'vortex_1': vortex_counts[1],
                        'vortex_2': vortex_counts[2],
                        'vortex_3': vortex_counts[3],
                        'n': n,
                        'k': k,
                        'distance': distance,
                        'logical_error_rate': logical_error_rate,
                        'error_bar': error_bar,
                        'shots': results_sinter.shots,
                        'errors': results_sinter.errors,
                        'p_phenomenological': p_phenomenological
                    }
                    
                    all_results.append(result)
                    
                    # Update best codes
                    key = (n, k)
                    is_zero_vortex = (vortex_counts == [0, 0, 0, 0])
                    
                    # Update best by distance
                    if distance is not None:
                        if key not in best_by_distance_arbitrary or \
                           distance > best_by_distance_arbitrary[key]['distance']:
                            best_by_distance_arbitrary[key] = result.copy()
                        
                        if is_zero_vortex:
                            if key not in best_by_distance_zero_vortex or \
                               distance > best_by_distance_zero_vortex[key]['distance']:
                                best_by_distance_zero_vortex[key] = result.copy()
                    
                    # Update best by error rate
                    if not np.isnan(logical_error_rate):
                        if key not in best_by_error_rate_arbitrary or \
                           logical_error_rate < best_by_error_rate_arbitrary[key]['logical_error_rate']:
                            best_by_error_rate_arbitrary[key] = result.copy()
                        
                        if is_zero_vortex:
                            if key not in best_by_error_rate_zero_vortex or \
                               logical_error_rate < best_by_error_rate_zero_vortex[key]['logical_error_rate']:
                                best_by_error_rate_zero_vortex[key] = result.copy()
                    
                    successful += 1
                    
                except Exception as e:
                    print(f"Error testing lattice {lattice_idx}, vortex {vortex_counts}: {e}")
                    failed += 1
                    continue
            
            # Checkpoint: save results periodically
            if (lattice_idx + 1) % checkpoint_interval == 0:
                _save_checkpoint(all_results, output_csv, result_fieldnames)
                _save_summary(
                    best_by_distance_arbitrary,
                    best_by_distance_zero_vortex,
                    best_by_error_rate_arbitrary,
                    best_by_error_rate_zero_vortex,
                    summary_csv
                )
                
        except Exception as e:
            print(f"Error processing lattice {lattice_idx}: {e}")
            failed += 1
            continue
    
    # Final save
    _save_checkpoint(all_results, output_csv, result_fieldnames)
    _save_summary(
        best_by_distance_arbitrary,
        best_by_distance_zero_vortex,
        best_by_error_rate_arbitrary,
        best_by_error_rate_zero_vortex,
        summary_csv
    )
    
    # Print summary
    print(f"\n=== Search Complete ===")
    print(f"Total configurations tested: {total_tested}")
    print(f"Successful: {successful}")
    print(f"Failed: {failed}")
    print(f"\nBest codes found for {len(set(k for n, k in best_by_distance_arbitrary.keys()))} unique (n,k) pairs")
    print(f"Detailed results saved to: {output_csv}")
    print(f"Summary saved to: {summary_csv}")


def _save_checkpoint(results: List[Dict], output_csv: str, fieldnames: List[str]):
    """Save checkpoint of results to CSV."""
    with open(output_csv, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results)


def _save_summary(
    best_by_distance_arbitrary: Dict[Tuple[int, int], Dict],
    best_by_distance_zero_vortex: Dict[Tuple[int, int], Dict],
    best_by_error_rate_arbitrary: Dict[Tuple[int, int], Dict],
    best_by_error_rate_zero_vortex: Dict[Tuple[int, int], Dict],
    summary_csv: str
):
    """Save summary of best codes to CSV."""
    summary_fieldnames = [
        'n', 'k', 'metric_type', 'vortex_type',
        'lattice_vec_0', 'lattice_vec_1', 'lattice_vec_2', 'lattice_vec_3',
        'vortex_0', 'vortex_1', 'vortex_2', 'vortex_3',
        'distance', 'logical_error_rate', 'error_bar',
        'shots', 'errors', 'p_phenomenological'
    ]
    
    summary_rows = []
    
    # Get all (n, k) pairs
    all_keys = set()
    all_keys.update(best_by_distance_arbitrary.keys())
    all_keys.update(best_by_distance_zero_vortex.keys())
    all_keys.update(best_by_error_rate_arbitrary.keys())
    all_keys.update(best_by_error_rate_zero_vortex.keys())
    
    for n, k in sorted(all_keys):
        # Distance - arbitrary
        if (n, k) in best_by_distance_arbitrary:
            result = best_by_distance_arbitrary[(n, k)]
            summary_rows.append({
                'n': n,
                'k': k,
                'metric_type': 'distance',
                'vortex_type': 'arbitrary',
                'lattice_vec_0': result['lattice_vec_0'],
                'lattice_vec_1': result['lattice_vec_1'],
                'lattice_vec_2': result['lattice_vec_2'],
                'lattice_vec_3': result['lattice_vec_3'],
                'vortex_0': result['vortex_0'],
                'vortex_1': result['vortex_1'],
                'vortex_2': result['vortex_2'],
                'vortex_3': result['vortex_3'],
                'distance': result['distance'],
                'logical_error_rate': result['logical_error_rate'],
                'error_bar': result['error_bar'],
                'shots': result['shots'],
                'errors': result['errors'],
                'p_phenomenological': result['p_phenomenological']
            })
        
        # Distance - zero vortex
        if (n, k) in best_by_distance_zero_vortex:
            result = best_by_distance_zero_vortex[(n, k)]
            summary_rows.append({
                'n': n,
                'k': k,
                'metric_type': 'distance',
                'vortex_type': 'zero_vortex',
                'lattice_vec_0': result['lattice_vec_0'],
                'lattice_vec_1': result['lattice_vec_1'],
                'lattice_vec_2': result['lattice_vec_2'],
                'lattice_vec_3': result['lattice_vec_3'],
                'vortex_0': result['vortex_0'],
                'vortex_1': result['vortex_1'],
                'vortex_2': result['vortex_2'],
                'vortex_3': result['vortex_3'],
                'distance': result['distance'],
                'logical_error_rate': result['logical_error_rate'],
                'error_bar': result['error_bar'],
                'shots': result['shots'],
                'errors': result['errors'],
                'p_phenomenological': result['p_phenomenological']
            })
        
        # Error rate - arbitrary
        if (n, k) in best_by_error_rate_arbitrary:
            result = best_by_error_rate_arbitrary[(n, k)]
            summary_rows.append({
                'n': n,
                'k': k,
                'metric_type': 'error_rate',
                'vortex_type': 'arbitrary',
                'lattice_vec_0': result['lattice_vec_0'],
                'lattice_vec_1': result['lattice_vec_1'],
                'lattice_vec_2': result['lattice_vec_2'],
                'lattice_vec_3': result['lattice_vec_3'],
                'vortex_0': result['vortex_0'],
                'vortex_1': result['vortex_1'],
                'vortex_2': result['vortex_2'],
                'vortex_3': result['vortex_3'],
                'distance': result['distance'],
                'logical_error_rate': result['logical_error_rate'],
                'error_bar': result['error_bar'],
                'shots': result['shots'],
                'errors': result['errors'],
                'p_phenomenological': result['p_phenomenological']
            })
        
        # Error rate - zero vortex
        if (n, k) in best_by_error_rate_zero_vortex:
            result = best_by_error_rate_zero_vortex[(n, k)]
            summary_rows.append({
                'n': n,
                'k': k,
                'metric_type': 'error_rate',
                'vortex_type': 'zero_vortex',
                'lattice_vec_0': result['lattice_vec_0'],
                'lattice_vec_1': result['lattice_vec_1'],
                'lattice_vec_2': result['lattice_vec_2'],
                'lattice_vec_3': result['lattice_vec_3'],
                'vortex_0': result['vortex_0'],
                'vortex_1': result['vortex_1'],
                'vortex_2': result['vortex_2'],
                'vortex_3': result['vortex_3'],
                'distance': result['distance'],
                'logical_error_rate': result['logical_error_rate'],
                'error_bar': result['error_bar'],
                'shots': result['shots'],
                'errors': result['errors'],
                'p_phenomenological': result['p_phenomenological']
            })
    
    with open(summary_csv, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=summary_fieldnames)
        writer.writeheader()
        writer.writerows(summary_rows)


if __name__ == '__main__':
    import argparse
    
    parser = argparse.ArgumentParser(description='Brute force search for optimal codes with vortices')
    parser.add_argument('--input', type=str, default='unique_4d_lattices.csv',
                        help='Input CSV file with unique lattices [default: unique_4d_lattices.csv]')
    parser.add_argument('--p-phenom', type=float, default=0., #0.02
                        help='Phenomenological error rate [default: 0.02]')
    parser.add_argument('--p-cx', type=float, default=0.001,
                        help='CNOT gate error rate [default: 0.0]')
    parser.add_argument('--shots', type=int, default=100000,
                        help='Shots per configuration [default: 100000]')
    parser.add_argument('--max-n', type=int, default=10000,
                        help='Maximum physical qubits [default: 10000]')
    parser.add_argument('--workers', type=int, default=10,
                        help='Number of parallel workers [default: 10]')
    parser.add_argument('--max-errors', type=int, default=100,
                        help='Maximum errors before stopping [default: 100]')
    parser.add_argument('--noisy-cycles', type=int, default=4,
                        help='Number of noisy cycles [default: 4]')
    parser.add_argument('--noiseless-init', type=int, default=3,
                        help='Number of initial noiseless cycles [default: 3]')
    parser.add_argument('--noiseless-final', type=int, default=3,
                        help='Number of final noiseless cycles [default: 3]')
    parser.add_argument('--basis', type=str, default='Z', choices=['Z', 'X'],
                        help='Measurement basis [default: Z]')
    parser.add_argument('--output', type=str, default='search_results.csv',
                        help='Output CSV for detailed results [default: search_results.csv]')
    parser.add_argument('--summary', type=str, default='best_codes_summary.csv',
                        help='Output CSV for best codes summary [default: best_codes_summary.csv]')
    parser.add_argument('--checkpoint', type=int, default=10,
                        help='Checkpoint interval (save every N lattices) [default: 10]')
    
    args = parser.parse_args()
    
    search_codes_with_vortices(
        input_csv=args.input,
        p_phenomenological=args.p_phenom,
        p_cx=args.p_cx,
        shots_per_point=args.shots,
        max_n=args.max_n,
        num_workers=args.workers,
        max_errors=args.max_errors,
        num_noisy_cycles=args.noisy_cycles,
        num_noiseless_cycles_init=args.noiseless_init,
        num_noiseless_cycles_final=args.noiseless_final,
        basis=args.basis,
        output_csv=args.output,
        summary_csv=args.summary,
        checkpoint_interval=args.checkpoint
    )

